[package]
name = "bevy_cronjob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ecs = "0.11.0"
cron = "0.12.0"
chrono = "0.4.19"

[dev-dependencies]
bevy = { version = "0.11.0", default-features = false, features = [] }

